# Generated by Django 4.2.28 on 2026-02-25 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_attente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('ESPECE', 'Espèce'), ('ORANGE_MONEY', 'Orange Money'), ('MOOV', 'Moov Africa')], max_length=50)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_attente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='file_attente.fileattente')),
            ],
        ),
    ]
