# Generated by Django 4.2.28 on 2026-02-11 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='statut',
        ),
    ]
