# Generated by Django 4.2.28 on 2026-02-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='metier',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('COIFFEUR', 'Coiffeur'), ('RECEPTIONNISTE', 'Réceptionniste')], default='RECEPTIONNISTE', max_length=20),
        ),
    ]
